services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/shawn/homelab/proxmox/docker:/home/shawn/homelab/proxmox/docker
    environment:
      - DOCKGE_STACKS_DIR=/home/shawn/homelab/proxmox/docker